services:
  db-postgres:
    image: postgres:16.4-alpine3.20
    hostname: db-postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=local_database
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis_password
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local
